version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
build:
  project: GGit.sln
  verbosity: minimal
after_build:
- ps: "Get-ChildItem \".\\GGit\\bin\" | ForEach-Object {if($_ -is [IO.fileinfo]){if($_.Extension -ne \".gha\" -and $_.Extension -ne \".dll\") {Remove-item -Force $_.FullName}}}; \n\n Get-ChildItem \".\\GGit\\bin\\lib\" | ForEach-Object {if ($_.Name -ne \"win32\") { Remove-Item -Recurse -Force $_.FullName}}"
artifacts:
- path: GGit/bin
  name: GGit
deploy:
- provider: GitHub
  auth_token:
    secure: wBRUgTcJLpK8LROfc4ufglCXIHsnxm/e4t5wWK4jgA+R16mIyZMCsajXNNuzwFDt
  draft: true